server {
        listen 80;

        
        location /.well-known/acme-challenge/ {
                root /var/www/certbot;
            }


        # =========================
        # FRONTEND (Angular)
        # =========================
        location / {
            proxy_pass http://frontend;
        }

        # =========================
        # BACKEND (Spring Boot)
        # =========================
        location /api/ {
            proxy_pass http://backend:8080/;
        }

}